#!/system/bin/sh
#SD-Card read ahead
#Reduce Overhead on SD-Card read

if /system/xbin/busybox [ -e /sys/devices/virtual/bdi/default/read_ahead_kb ]; then
    echo $1 > /sys/devices/virtual/bdi/default/read_ahead_kb;
fi;

echo $2 > /sys/devices/virtual/bdi/179:0/read_ahead_kb
echo $2 > /sys/devices/virtual/bdi/179:8/read_ahead_kb

echo $3 > /sys/devices/virtual/bdi/138:9/read_ahead_kb
echo $3 > /sys/devices/virtual/bdi/138:10/read_ahead_kb
echo $3 > /sys/devices/virtual/bdi/138:11/read_ahead_kb
