#!/system/bin/sh
#Schedulers
#Change I/O scheduler
#ROW I/O

insmod /system/lib/modules/row-iosched.ko

MTD=`ls -d /sys/block/mtd*`;
MMC=`ls -d /sys/block/mmc*`;

for i in $MTD $MMC; do 
    echo "row" > "$i"/queue/scheduler;
done;

sleep 1
rmmod deadline_iosched
rmmod cfq_iosched
rmmod sio_iosched
